<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<?php if ($packageData = $block->getData('package_data')): ?>
    <table>
        <thead>
            <tr>
                <th><strong><?= $escaper->escapeHtml(__('Package')); ?></strong></th>
                <th><strong><?= $escaper->escapeHtml(__('Version')); ?></strong></th>
                <th><strong><?= $escaper->escapeHtml(__('Verdict')); ?></strong></th>
                <th><strong><?= $escaper->escapeHtml(__('Percentage')); ?></strong></th>
                <th><strong><?= $escaper->escapeHtml(__('Checksum')); ?></strong></th>
                <th><strong><?= $escaper->escapeHtml(__('Package ID')); ?></strong></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($packageData as $data): ?>
                <tr>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['name']); ?></td>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['version']); ?></td>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['verdict']); ?></td>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['percentage']); ?></td>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['checksum']); ?></td>
                    <td style="padding: 10px;"><?= $escaper->escapeHtml($data['id']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
